import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{ShieldCheck,LayoutDashboard,Search,Upload,Network,FileWarning}from'lucide-react';import'./style.css';
const API='http://localhost:8000/api';
function App(){const[sum,setSum]=useState<any>({});const[cases,setCases]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const[tab,setTab]=useState('Overview');const[q,setQ]=useState('');
const load=()=>{fetch(API+'/dashboard/summary').then(r=>r.json()).then(setSum);fetch(API+'/cases').then(r=>r.json()).then(setCases)};useEffect(load,[]);
const open=(id:string)=>fetch(API+'/cases/'+id).then(r=>r.json()).then(setSelected);
const upload=async(e:any)=>{let f=e.target.files?.[0];if(!f)return;let fd=new FormData();fd.append('file',f);let r=await fetch(API+'/upload',{method:'POST',body:fd});alert((await r.json()).message||'Upload failed');load()};
return <div className="app"><aside><div className="brand"><ShieldCheck/> PROCUREX</div><small>PROCUREMENT INTELLIGENCE</small>{['Overview','Investigation Cases','Procurements','Relationships','Upload Data'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x==='Overview'?<LayoutDashboard/>:x==='Investigation Cases'?<FileWarning/>:x==='Relationships'?<Network/>:x==='Upload Data'?<Upload/>:<Search/>}{x}</button>)}</aside><main><header><div><h1>{tab}</h1><p>Automated Public Procurement Anomaly Detection</p></div><span className="human">Human-in-the-loop decision support</span></header>
{tab==='Overview'&&<><section className="cards">{[['Tenders',sum.tenders],['Vendors',sum.vendors],['Procurement Value','₹'+((sum.value||0)/1e7).toFixed(1)+' Cr'],['Flagged Cases',sum.flagged],['Critical Review',sum.critical]].map(([a,b])=><div className="card"><small>{a}</small><strong>{b}</strong></div>)}</section><section className="panel"><h2>Investigation Priority Queue</h2><p>Cases are prioritized from statistical, behavioral and machine-learning signals. A flag is not a finding of wrongdoing.</p><CaseTable cases={cases.slice(0,10)} open={open}/></section></>}
{tab==='Investigation Cases'&&<section className="panel"><div className="row"><div><h2>Investigation Cases</h2><p>Explainable signals requiring human review.</p></div><input placeholder="Search cases..." value={q} onChange={e=>setQ(e.target.value)}/></div><CaseTable cases={cases.filter(c=>JSON.stringify(c).toLowerCase().includes(q.toLowerCase()))} open={open}/></section>}
{tab==='Procurements'&&<section className="panel"><h2>Procurement Explorer</h2><p>Open Investigation Cases to inspect prioritized procurement records and evidence.</p></section>}
{tab==='Relationships'&&<section className="panel"><h2>Relationship Intelligence</h2><p>Vendor-to-tender and shared-attribute relationships are evaluated as supporting signals, never as proof of misconduct.</p><div className="network">Vendor A ── BID_ON ── Tender T-5100 ── WON_BY ── Vendor B<br/>Vendor A ── SAME_ADDRESS ── Vendor C</div></section>}
{tab==='Upload Data'&&<section className="panel"><h2>Analyze a Procurement Dataset</h2><p>Upload a compatible CSV (maximum 5 MB). The backend recalculates anomaly and investigation-priority signals.</p><label className="drop">Choose CSV<input type="file" accept=".csv" onChange={upload}/></label></section>}
</main>{selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><small>{selected.case_id}</small><h2>{selected.title}</h2><div className="score"><strong>{selected.priority}</strong><span>/100<br/>{selected.level}</span></div><p>{selected.reason}</p><div className="facts"><span>Department<b>{selected.department}</b></span><span>Winning vendor<b>{selected.vendor}</b></span><span>Estimated<b>₹{selected.estimated.toLocaleString()}</b></span><span>Contract<b>₹{selected.contract.toLocaleString()}</b></span></div><h3>Why this case was flagged</h3>{selected.signals.map((s:any)=><div className="signal"><div><b>{s.name}</b><p>{s.evidence}</p></div><strong>{s.score}</strong></div>)}<div className="notice">These signals identify activity for human review and do not establish corruption, fraud or collusion.</div></div></div>}</div>}
function CaseTable({cases,open}:any){return <div className="table">{cases.map((c:any)=><div className="tr" onClick={()=>open(c.case_id)}><b>{c.case_id}</b><span>{c.department}</span><span>{c.vendor}</span><span>{c.pattern}</span><strong className={c.priority>=80?'red':'amber'}>{c.priority}</strong></div>)}</div>};createRoot(document.getElementById('root')!).render(<App/>);
